#!/usr/bin/env bash
# This script displays numbers from 1 to 100
# For multiples of 3: prints "Fizz"
# For multiples of 5: prints "Buzz"
# For multiples of both 3 and 5: prints "FizzBuzz"

for num in {1..100}
do
  if (( num % 3 == 0 && num % 5 == 0 )); then
    echo "FizzBuzz"
  elif (( num % 3 == 0 )); then
    echo "Fizz"
  elif (( num % 5 == 0 )); then
    echo "Buzz"
  else
    echo "$num"
  fi
done
