#!/usr/bin/env bash
# This script displays numbers from 1 to 20,
# and prints special messages for superstitious numbers:
# 4 -> bad luck from China
# 9 -> bad luck from Japan
# 17 -> bad luck from Italy

count=1

while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  ((count++))
done
