#!/usr/bin/env bash
# This script displays a list of all currently running processes in a user-oriented format with hierarchy

ps -e --forest -o user,pid,%cpu,%mem,vsz,rss,tty,stat,start,time,command
